# Generated by Django 5.2.8 on 2025-12-16 09:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='مشتری ناشناخته', max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_region', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carpet', 'فرش'), ('tableau', 'تابلو فرش')], max_length=20)),
                ('branch', models.CharField(choices=[('abrisham_qom', 'ابریشم طرح قم'), ('tabriz', 'تبریز'), ('naein', 'نائین'), ('hood_birjand', 'هود بیرجند'), ('qashqai', 'قشقایی'), ('arak', 'اراک'), ('qom', 'قم'), ('torkaman', 'ترکمن'), ('esfahan', 'اصفهان'), ('saregh', 'سارق'), ('ashayeri', 'عشایری'), ('bakhtiar', 'بختیار'), ('ardakan', 'اردکان'), ('kashan', 'کاشان'), ('kashm', 'کاشم'), ('other_carpet', 'متفرقه'), ('gol', 'گل'), ('fransi', 'فرانسوی'), ('mazhabi', 'مذهبی'), ('animal', 'حیوان و پرنده'), ('other_tableau', 'متفرقه'), ('abrisham_qom', 'ابریشم طرح قم'), ('chehre', 'چهره'), ('tarikhi', 'تاریخی'), ('manzare', 'منظره')], max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('crop_sex', models.CharField(blank=True, choices=[('chele nakh abrisham', 'چله نخ ابریشم'), ('chele abrisham', 'چله ابریشم')], max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='unit_price_non_negative'), models.CheckConstraint(condition=models.Q(('sale_price__gte', 0), ('sale_price__isnull', True), _connector='OR'), name='sale_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
