# Generated by Django 5.2.8 on 2025-12-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('carpet', 'فرش'), ('tableau', 'تابلو فرش'), ('worked', 'کار کرده')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_city'], name='main_app_or_custome_384a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_state'], name='main_app_or_custome_beb986_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_region'], name='main_app_or_custome_e8da29_idx'),
        ),
    ]
